name: esim
recipe: laravel
config:
  via: nginx
  php: 8.1
  webroot: public
  database: mysql

services:
  database:
    type: mysql
    portforward: 3311
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
#
#  pma:
#    type: phpmyadmin
#    hosts:
#      - database

proxy:
  mailhog:
    - mailhog.lndo.site
#  pma:
#    - pma.lndo.site